spring:
  kafka:
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.nelson.notificationservice.OrderPlaceEvent
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers: localhost:9092
  sleuth:
    integration:
      enabled: 'true'
    sampler:
      probability: '1'
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: notification-service
server:
  port: '0'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
