server:
  port: 0
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/techie_product
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka