server:
  port: 0
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/techie_inventory
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: 'create-drop'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka